# This file is machine-generated - editing it directly is not advised

[[Currencies]]
deps = ["DelimitedFiles"]
git-tree-sha1 = "c655dfa5647565eedc405e1dcfe0775bb1837275"
repo-rev = "master"
repo-url = "https://github.com/JuliaFinance/Currencies.jl.git"
uuid = "0fd90b74-7c1f-579e-9252-02cd883047b9"
version = "0.0.1"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
