name = "Countries"
uuid = "d5396ca0-2cf9-11e9-2c96-2532c40e11ac"
authors = ["Eric Forgy <Eric.Forgy@coherentasia.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ISOCurrencies = "5683cba2-2ced-11e9-0d3f-33b1fe4e9d91"
